//Current year for footer
window.onload = function() {
    let date = new Date().getFullYear();
    document.getElementById("year").innerHTML = date;
}

//Array of classic Disney movies
movies = [
    "Snow White and the Seven Dwarfs",
    "Fantasia",
    "Pinocchio",
    "Dumbo",
    "Bambi",
    "Saludos Amigos",
    "The Three Caballeros",
    "The Adventures of Ichabod and Mr. Toad",
    "Cinderella",
    "Alice in Wonderland",
    "Peter Pan",
    "Lady and the Tramp",
    "Sleeping Beauty",
    "101 Dalmatians",
    "The Sword in the Stone",
    "The Jungle Book",
    "The Aristocats",
    "Robin Hood",
    "The Many Adventures of Winnie the Pooh",
    "The Rescuers",
    "The Fox and the Hound",
    "The Black Cauldron",
    "Basil - The Great Mouse Detective",
    "Oliver and Company",
    "The Little Mermaid",
    "DuckTales: The Movie - Treasure of the Lost Lamp",
    "The Rescuers Down Under",
    "Beauty and the Beast",
    "Aladdin",
    "The Nightmare Before Christmas",
    "The Lion King",
    "Pocahontas",
    "A Goofy Movie",
    "Toy Story",
    "The Hunchback of Notre Dame",
    "Beauty and the Beast: The Enchanted Christmas",
    "Hercules",
    "The Lion King II: Simba's Pride",
    "A Bug's Life",
    "Pocahontas II: Journey to a New World",
    "Mulan",
    "Tarzan",
    "Mickey's Once Upon a Christmas",
    "Toy Story 2",
    "Fantasia",
    "Fantasia 2000",
    "Dinosaur",
    "The Little Mermaid II: Return to the Sea",
    "The Emperor's New Groove",
    "An Extremely Goofy Movie",
    "The Tigger Movie",
    "Lady and the Tramp II: Scamp's Adventure",
    "Monsters, Inc",
    "Atlantis: The Lost Empire",
    "Mickey's Magical Christmas: Snowed in at the House of Mouse",
    "Winnie the Pooh: A Very Merry Christmas",
    "Treasure Planet",
    "Lilo & Stitch",
    "Cinderella II: Dreams Come True",
    "Return to Never Land",
    "Piglet's Big Movie",
    "The Jungle Book 2",
    "Atlantis: Milo's Return",
    "101 Dalmatians 2: Patch's London Adventure",
    "Brother Bear",
    "Finding Nemo",
    "Winnie the Pooh: Springtime with Roo",
    "The Lion King 1½",
    "The Incredibles",
    "Mickey's Twice Upon a Christmas",
    "Mulan II",
    "The Three Musketeers",
    "Kronk's New Groove",
    "Lilo & Stitch 2: Stitch Has a Glitch",
    "Pooh's Heffalump Movie",
    "Chicken Little",
    "Pooh's Heffalump Halloween Movie",
    "Cars",
    "Bambi II",
    "The Fox and the Hound 2",
    "Brother Bear 2",
    "Meet the Robinsons",
    "Cinderella III: A Twist in Time",
    "Ratatouille",
    "My Friends Tigger and pooh, Super Sleuth Christmas",
    "Little Mermaid III - Ariel's Beginning",
    "Tinker Bell",
    "Bolt",
    "Wall-E",
    "A Christmas Carol",
    "Up",
    "The Princess and the Frog",
    "Tangled",
    "Toy Story 3",
    "Winnie the Pooh",
    "Cars 2",
    "Frankenweenie",
    "Wreck-It Ralph",
    "Brave",
    "Planes",
    "Frozen",
    "Monsters University",
    "Big Hero 6",
    "Planes: Fire Rescue",
    "The Good Dinosaur",
    "Inside Out",
    "Finding Dory",
    "Zootopia",
    "Moana",
    "Coco",
    "Cars 3",
    "Toy Story 4",
    "The Incredibles 2",
    "Frozen 2",
    "Wreck-It Ralph 2",
    "Onward",
    "Soul",
    "Luca",
    "Raya and the Last Dragon",
    "Encanto",
    "Ron's Gone Wrong"
];

//Pick random movie from array when user clicks on button
function randomMovie() {
    const random_movie = movies[Math.floor(Math.random() * movies.length)];
    document.getElementById("result").innerHTML=random_movie;
}

//Pick random movie from array when user hits enter key or space key
//Accessibility purpose
document.addEventListener('keyup', (event) => {
    if (event.key === "Enter" || event.code === "Space") {
        randomMovie();
    }
  });